-- deshacer_insertar_ejercicios_fitcron.sql
-- Borrado best-effort de lo insertado recientemente por insertar_ejercicios_fitcron.sql.
-- NOTA: usa un filtro por created_at reciente para aproximar el rollback.
-- intervalo creado: created_at >= (now() - interval '2 hours')
-- Candidatos: public.tipo_ejercicio (catálogo) con usuario_id is null y nombre en la lista del CSV.
-- Orden: serie -> ejercicio -> rutina_ejercicio -> tipo_ejercicio (respeta FKs).

begin;

-- 0) Determinar ids objetivo en una tabla temporal (CTE no persiste entre sentencias).
create temporary table target_ids (
  id uuid primary key
) on commit drop;

insert into target_ids(id)
select te.id
from public.tipo_ejercicio te
where te.usuario_id is null
  and te.created_at >= (now() - interval '2 hours')
  and te.nombre in (
  'Abdominales en V con Mancuerna',
  'Aductor Externo Aislado en Máquina',
  'Aductor Externo en Máquina',
  'Aductor Externo en Polea',
  'Aductor Interno Aislado en Máquina',
  'Aductor Interno en Máquina',
  'Aductor Interno en Polea Baja',
  'Air Bike',
  'Apertura Aislada Declinada con Polea',
  'Apertura Aislada en Punta',
  'Aperturas con Bandas',
  'Aperturas con Mancuernas',
  'Aperturas Declinadas con giro con Mancuernas',
  'Aperturas Declinadas con Mancuernas',
  'Aperturas en Máquina',
  'Aperturas Extendidas en Máquina',
  'Aperturas Inclinadas con Mancuernas',
  'Aperturas Traseras en Pronación en Máquina',
  'Aperturas Traseras Neutras en Máquina',
  'Bicicleta Estática Deportiva',
  'Bicicleta Estática Normal',
  'Bicicleta Estática Reclinada',
  'Brazada en Fitball',
  'Buenos días con Barra',
  'Burpee',
  'Burpee con Mancuernas',
  'Burpee Jack',
  'Butt Kicks',
  'Caminar',
  'Caminar a paso ligero',
  'Caminar con peso',
  'Caminar con rodilla arriba',
  'Caminar en cuclillas',
  'Carrera con salto',
  'Carrera continua',
  'Carrera de pasos cortos',
  'Carrera de skater',
  'Carrera en Cinta',
  'Carrera en Cinta Inclinada',
  'Carrera en zigzag',
  'Carrera hacia atrás',
  'Carrera rápida en el sitio',
  'Cocoons',
  'Cruce completo de Poleas',
  'Cruce de Poleas',
  'Cruce inferior de Poleas',
  'Cruce superior de Poleas',
  'Cruces en Máquina',
  'Crunch Cruzado',
  'Crunch Cruzado con Bandas',
  'Crunch Cruzado con piernas elevadas',
  'Crunch Cruzado estirado',
  'Crunch Diagonal de pie con Bandas',
  'Crunch Diagonal de rodillas con Bandas',
  'Crunch Diagonal en Polea',
  'Crunch Doble Vertical en Máquina',
  'Crunch en Decúbito Lateral con curl de bíceps',
  'Crunch en Plancha Lateral',
  'Crunch Frog',
  'Crunch Horizontal en Silla Romana',
  'Crunch Inferior con flexión y extensión',
  'Crunch Inferior con Rodillas Flexionadas',
  'Crunch Inferior Cruzado',
  'Crunch Inferior Cruzado Alterno',
  'Crunch Inferior en círculos',
  'Crunch Inferior en Máquina Smith',
  'Crunch Inferior en Polea',
  'Crunch Inferior Horizontal en Máquina',
  'Crunch Inferior Inclinado con piernas estiradas',
  'Crunch Inferior sentado',
  'Crunch Inferior sentado en banco',
  'Crunch Lateral con Barra',
  'Crunch Lateral con Mancuerna',
  'Crunch Lateral de pie con Banda',
  'Crunch Lateral de pie en Polea Alta',
  'Crunch Lateral de pie en Polea Baja',
  'Crunch Lateral en soporte',
  'Crunch Lateral Horizontal Alterno',
  'Crunch Lateral Horizontal Concentrado',
  'Crunch Lateral Inclinado',
  'Crunch Superior',
  'Crunch Superior Concentrado Elevado',
  'Crunch Superior Cruzado',
  'Crunch Superior Cruzado Concentrado',
  'Crunch Superior Cruzado Concentrado Elevado',
  'Crunch Superior Cruzado Declinado',
  'Crunch Superior de pie con Bandas',
  'Crunch Superior de pie con Polea delante',
  'Crunch Superior de rodillas con Polea',
  'Crunch Superior Declinado',
  'Crunch Superior en Fitball',
  'Crunch Superior Horizontal en Máquina',
  'Crunch Superior sentado con Polea',
  'Crunch Superior Vertical Amplio en Máquina',
  'Crunch Superior Vertical en Máquina',
  'Cuarto de Sentadilla con Barra',
  'Cuarto de Sentadilla con Mancuernas',
  'Curl a una mano en Polea Alta',
  'Curl Aislado con Barra',
  'Curl Aislado en Pronación con Mancuerna',
  'Curl Aislado en Pronación en Polea Baja',
  'Curl Aislado en Supinación con Mancuerna',
  'Curl Aislado en Supinación en Polea Baja',
  'Curl Aislado hacia abajo con Mancuerna',
  'Curl Aislado Largo en Supinación en Polea Baja',
  'Curl Aislado Neutro con Mancuerna',
  'Curl Alterno en Supinación en Máquina',
  'Curl con giro Alterno con Mancuernas',
  'Curl con peso libre',
  'Curl Concentrado Cerrado con Barra',
  'Curl Concentrado Cerrado con Barra Z',
  'Curl Concentrado Cerrado en Polea Baja',
  'Curl Concentrado con Barra',
  'Curl Concentrado de Dedos con Barra',
  'Curl Concentrado en Máquina',
  'Curl Concentrado en Pronación con Banda',
  'Curl Concentrado en Pronación con Barra',
  'Curl Concentrado en Pronación con Mancuerna',
  'Curl Concentrado en Pronación con Polea',
  'Curl Concentrado en Supinación con Banda',
  'Curl Concentrado en Supinación con Barra',
  'Curl Concentrado en Supinación con Mancuerna',
  'Curl Concentrado en Supinación con Polea',
  'Curl Concentrado en Supinación en Polea Baja',
  'Curl Concentrado Frontal Aislado en Supinación en Polea Baja',
  'Curl Concentrado Lateral Aislado en Supinación en Polea Baja',
  'Curl Concentrado Neutral con Mancuerna',
  'Curl en Banco Scott en Pronación Aislado con Polea',
  'Curl en Banco Scott en Pronación con Mancuerna',
  'Curl en Banco Scott en Pronación con Polea',
  'Curl en Banco Scott en Supinación Aislado con Polea',
  'Curl en Banco Scott en Supinación con Mancuerna',
  'Curl en Banco Scott en Supinación con Polea',
  'Curl en Banco Scott Neutro Aislado con Polea',
  'Curl en Banco Scott Neutro con Mancuerna',
  'Curl en Banco Scott Neutro con Polea',
  'Curl en caída con Bandas',
  'Curl en Martillo Alterno con Mancuernas',
  'Curl en Martillo con Barra',
  'Curl en Martillo Cruzado con Mancuernas',
  'Curl en Martillo en Máquina Scott',
  'Curl en Martillo en Polea Alta',
  'Curl en Martillo en Polea Baja',
  'Curl en Pronación Abierto con Barra',
  'Curl en Pronación con agarre Z en Polea Baja',
  'Curl en Pronación con Barra',
  'Curl en Pronación con Barra Z',
  'Curl en Pronación en banco Scott con Barra',
  'Curl en Pronación en banco Scott con Barra Z',
  'Curl en Pronación en Máquina Scott',
  'Curl en Supinación Abierto Con Barra',
  'Curl en Supinación Abierto Con Barra Z',
  'Curl en Supinación Abierto en banco Scott con Barra Z',
  'Curl en Supinación Aislado con Banda',
  'Curl en Supinación Alterno con Bandas',
  'Curl en Supinación Cerrado con Barra',
  'Curl en Supinación Cerrado Con Barra Z',
  'Curl en Supinación Cerrado en banco Scott con Barra Z',
  'Curl en Supinación Cerrado en Polea Baja',
  'Curl en Supinación con agarre Z en Polea Baja',
  'Curl en Supinación con Bandas',
  'Curl en Supinación con Barra',
  'Curl en Supinación con Barra Z',
  'Curl en Supinación Concentrado con Banda',
  'Curl en Supinación Corto con Barra Z',
  'Curl en Supinación en banco Scott con Barra',
  'Curl en Supinación en Máquina Scott',
  'Curl en Supinación en Polea Alta',
  'Curl en Supinación en Polea Baja',
  'Curl en Supinación hacia abajo con Barra',
  'Curl en Supinación hacia abajo con Barra Z',
  'Curl en Supinación Retraído con Barra',
  'Curl en Supinación Retraído en Polea Baja',
  'Curl en V en Polea Baja',
  'Curl Femoral Aislado en Máquina',
  'Curl Femoral Horizontal en Máquina',
  'Curl Femoral Libre',
  'Curl Femoral Libre Asistido con Polea',
  'Curl Femoral Vertical en Máquina',
  'Curl Femoral Vertical en Polea',
  'Curl Horizontal Cerrado en Supinación con Polea',
  'Curl Horizontal con giro con Mancuernas',
  'Curl Horizontal con Mancuernas',
  'Curl Horizontal en Supinación con Mancuernas',
  'Curl Horizontal en Supinación con Polea',
  'Curl Horizontal Inclinado con Polea',
  'Curl Inclinado Alterno en Supinación con Mancuernas',
  'Curl Inclinado con Barra',
  'Curl Inclinado con giro Alterno con Mancuernas',
  'Curl Inclinado Lateral con Mancuernas',
  'Curl Inclinado Neutro Alterno con Mancuernas',
  'Curl Lateral con Mancuernas',
  'Curl Lateral en Supinación Aislado con Polea',
  'Curl Lateral en Supinación con Polea',
  'Curl Spider Aislado en Pronación con Mancuerna',
  'Curl Spider Aislado en Supinación con Mancuerna',
  'Curl Spider Aislado Neutro con Mancuerna',
  'Curl Spider en Pronación con Barra',
  'Curl Spider en Supinación con Barra',
  'Curl Spider en Supinación con Barra Z',
  'Curl Spider Neutro con Mancuerna',
  'Curl Vertical de Dedos con Barra',
  'Curl Vertical en Polea Baja',
  'Curl Vertical en Supinación con Barra',
  'Curl Vertical en Supinación con Polea',
  'Desplazamientos de Boxeo',
  'Dominada',
  'Dominada a una mano',
  'Dominada a una mano asistida',
  'Dominada Abierta',
  'Dominada Cerrada',
  'Dominada Cerrada Corta',
  'Dominada Cerrada en Martillo',
  'Dominada Circular en Supinación',
  'Dominada en Supinación',
  'Dominada Invertida',
  'Dominada Lateral',
  'Dominada Mixta',
  'Dominada Trasera',
  'Elevación Completa con Barra',
  'Elevación de Cadera con flexión de rodillas v1',
  'Elevación de Cadera con flexión de rodillas v2',
  'Elevación de Cadera con piernas estiradas',
  'Elevación de Cadera con piernas estiradas v2',
  'Elevación de Cadera con piernas flexionadas',
  'Elevación de piernas alternas Colgado',
  'Elevación de piernas colgado con Polea',
  'Elevación de piernas con Bandas',
  'Elevación de Piernas con torsión en soporte',
  'Elevación de piernas en Fitball',
  'Elevación de piernas estiradas Colgado',
  'Elevación de piernas estiradas en soporte',
  'Elevación de piernas flexionadas Colgado',
  'Elevación de piernas flexionadas en soporte',
  'Elevación de piernas laterales Colgado',
  'Elevación de rodillas',
  'Elevación de rodillas con apoyo',
  'Elevación Frontal Aislada en Polea',
  'Elevación Frontal Cerrada en Pronación con Barra',
  'Elevación Frontal con giros con Barra Z',
  'Elevación Frontal con Mancuerna',
  'Elevación Frontal Declinada Abierta con Barra Z',
  'Elevación Frontal Declinada con Mancuerna',
  'Elevación Frontal Declinada en Pronación con Barra',
  'Elevación Frontal en Polea',
  'Elevación Frontal en Pronación con Barra',
  'Elevación Frontal Horizontal en Polea',
  'Elevación Frontal Inclinada en Polea',
  'Elevación Frontal Inclinada en Supinación con Barra Z',
  'Elevación Lateral Aislada con Banda',
  'Elevación Lateral Aislada en Polea',
  'Elevación Lateral Concentrada en Polea',
  'Elevación Lateral en Punta',
  'Elevación Lateral Horizontal Aislada con Mancuerna',
  'Elevación Lateral Horizontal en Polea',
  'Elevación Lateral Inclinada Aislada con Mancuerna',
  'Elevación Total Colgado',
  'Elevación Trasera con Barra',
  'Elevaciones Circulares con Mancuernas',
  'Elevaciones Completas con Bandas',
  'Elevaciones Completas con Mancuernas',
  'Elevaciones Frontales con Banda',
  'Elevaciones Frontales Declinadas en Pronación con Mancuernas',
  'Elevaciones Frontales Declinadas Neutras con Mancuernas',
  'Elevaciones Frontales en Pronación con Mancuernas',
  'Elevaciones Frontales en Supinación con Mancuernas',
  'Elevaciones Frontales Inclinadas con giro con Mancuernas',
  'Elevaciones Frontales Inclinadas en Pronación con Mancuernas',
  'Elevaciones Lateral - Frontal Alto con Mancuernas',
  'Elevaciones Lateral - Frontal con Mancuernas',
  'Elevaciones Laterales con Banda',
  'Elevaciones Laterales Declinadas con Mancuernas',
  'Elevaciones Laterales Declinadas en Pronación con Mancuernas',
  'Elevaciones Laterales Declinadas en Supinación con Mancuernas',
  'Elevaciones Laterales Declinadas Neutras con Mancuernas',
  'Elevaciones Laterales Delanteras con Mancuernas',
  'Elevaciones Laterales en Máquina',
  'Elevaciones Laterales en Supinación con Mancuernas',
  'Elevaciones Laterales Horizontales con Mancuernas',
  'Elevaciones Laterales Neutras con Mancuernas',
  'Encogimiento Aislado con Mancuerna',
  'Encogimientos con Banda',
  'Encogimientos con Mancuernas',
  'Encogimientos Concentrados en Máquina',
  'Encogimientos Declinados con Mancuernas',
  'Encogimientos Delanteros con Barra',
  'Encogimientos en Máquina',
  'Encogimientos en Paralelas',
  'Encogimientos en Polea',
  'Encogimientos en Press Militar con Barra',
  'Encogimientos Horizontales en Polea',
  'Encogimientos Inclinados con Mancuernas',
  'Encogimientos Laterales con Mancuernas',
  'Encogimientos Libres en Banco',
  'Encogimientos Sentado con Barra',
  'Encogimientos Traseros con Barra',
  'Extensión Concentrada en Polea Alta',
  'Extensión Concentrada en Polea Baja',
  'Extensión de Cuádriceps Aislada con Banda',
  'Extensión de Cuádriceps con Barra',
  'Extensión de Cuádriceps en Máquina',
  'Extensión de Gemelo Aislado con Banda',
  'Extensión de Gemelo Aislado Delantero con Banda',
  'Extensión de Gemelo Aislado en Polea',
  'Extensión de Gemelo Aislado sentado con Mancuerna',
  'Extensión de Gemelos con Banda',
  'Extensión de Gemelos Concentrada en Máquina',
  'Extensión de Gemelos de pie',
  'Extensión de Gemelos de pie con Barra',
  'Extensión de Gemelos de pie con Mancuernas',
  'Extensión de Gemelos Declinada en Máquina',
  'Extensión de Gemelos en Máquina con carga Inferior',
  'Extensión de Gemelos en Máquina con carga Superior',
  'Extensión de Gemelos en Polea',
  'Extensión de Gemelos en Prensa',
  'Extensión de Gemelos Inclinada en Máquina',
  'Extensión de Gemelos sentado con Barra',
  'Extensión de Gemelos sentado con Mancuerna',
  'Extensión de Gemelos sentado en Máquina',
  'Extensión de Glúteos en Polea',
  'Extensión Declinada con Mancuernas',
  'Extensión Delante-Detrás con Mancuernas',
  'Extensión Diagonal en Polea Baja',
  'Extensión en caída con Bandas',
  'Extensión Frontal Aislada con Banda',
  'Extensión Frontal Aislada en Polea Alta',
  'Extensión Frontal con Arnés',
  'Extensión Frontal con Disco',
  'Extensión Frontal en Máquina',
  'Extensión Frontal en Polea',
  'Extensión hacia abajo con Bandas',
  'Extensión Horizontal con Barra',
  'Extensión Horizontal con Barra Z',
  'Extensión Horizontal Concentrada Interna con Mancuerna',
  'Extensión Horizontal Concentrada Superior con Mancuerna',
  'Extensión Horizontal en Martillo en Polea Alta',
  'Extensión Inclinada con Barra Z',
  'Extensión Lateral Aislada con Banda',
  'Extensión Lateral Aislada en Supinación en Polea Alta',
  'Extensión Lateral con Arnés',
  'Extensión Lateral en Máquina',
  'Extensión Trasera Aislada en Polea Alta',
  'Extensión Trasera Aislada en Polea Baja',
  'Extensión Trasera con Barra',
  'Extensión Trasera en Máquina',
  'Extensión Vertical Aislada con Mancuerna',
  'Extensión Vertical Aislada en Pronación en Polea Alta',
  'Extensión Vertical Aislada en Pronación en Polea Baja',
  'Extensión Vertical Aislada en Supinación en Polea Alta',
  'Extensión Vertical con Bandas',
  'Extensión Vertical con Barra Z',
  'Extensión Vertical con Mancuerna',
  'Extensión Vertical en Pronación en Polea Alta',
  'Extensión Vertical en Pronación en Polea Baja',
  'Extensión Vertical en Supinación en Polea Alta',
  'Extensión Vertical Neutra en Polea Alta',
  'Extensión Vertical Neutra en Polea Baja',
  'Extensiones Concentradas en Polea Alta',
  'Extensiones Cruzadas en Polea',
  'Extensiones Cruzadas en Polea Alta',
  'Extensiones en caída libre',
  'Extensiones en Máquina',
  'Extensiones en Pronación en Máquina',
  'Extensiones Horizontales Internas con Mancuernas',
  'Extensiones Inclinadas con Mancuernas',
  'Extensiones Laterales Amplias con Banda',
  'Extensiones Laterales con Banda',
  'Flexión Frontal con Disco',
  'Flexión Frontal en Polea',
  'Flexiones',
  'Flexiones a una mano',
  'Flexiones a una mano asistidas',
  'Flexiones Abiertas',
  'Flexiones Archer',
  'Flexiones Básicas',
  'Flexiones Cerradas',
  'Flexiones con codos',
  'Flexiones con Soportes',
  'Flexiones Cruzadas',
  'Flexiones Declinadas',
  'Flexiones Diamante',
  'Flexiones en supinación',
  'Flexiones Pliométricas',
  'Flexiones Pliométricas con Palmada',
  'Flexiones Verticales con Banco',
  'Flexiones Verticales entre Bancos',
  'Fondos Cerrados en Paralelas',
  'Fondos Coreanos en Barra',
  'Fondos en banco',
  'Fondos en Barra',
  'Fondos en Máquina',
  'Fondos en Paralelas',
  'Fondos en Pronación en Máquina',
  'Fondos entre bancos',
  'Fondos Imposibles',
  'Giros de cintura de pie con Banda',
  'Giros de cintura doblado con Barra',
  'Giros de cintura sentado con Barra',
  'Giros de cintura sentado con Polea',
  'Giros Inferiores de Oblicuos en Máquina',
  'Giros sentado en Fitball',
  'Giros Superiores de Oblicuos en Máquina',
  'Giros Superiores Sentado',
  'Giros Superiores Sentado con peso',
  'Golpes alternos',
  'Half Wipers con piernas estiradas',
  'Half Wipers con piernas flexionadas',
  'Hand Grip',
  'Hip Thrust Aislado con Barra',
  'Hip Thrust con Banda',
  'Hip Thrust con Barra',
  'Hip Thrust con Mancuerna',
  'Hip Thrust Declinado con Barra',
  'Hip Thrust Inclinado con Barra',
  'Hiperextensiones',
  'Hiperextensiones en Fitball',
  'Hiperextensiones en Máquina',
  'Hiperextensiones Inclinadas',
  'Hollow Hold',
  'Inclinación diagonal en Polea',
  'Jackknife Sit-Up',
  'Jalón Abierto Doble Neutro en Polea Alta',
  'Jalón Abierto en Pronación en Polea Alta',
  'Jalón Abierto en Supinación en Polea Alta',
  'Jalón Abierto Neutro en Polea Alta',
  'Jalón Aislado en Polea Alta',
  'Jalón Aislado Prono-Neutro en Polea Alta',
  'Jalón Aislado Prono-Supino en Polea Alta',
  'Jalón Cerrado con Cuerda en Polea Alta',
  'Jalón Cerrado en Pronación en Polea Alta',
  'Jalón Cerrado Neutro con Inclinación en Polea Alta',
  'Jalón Cerrado Neutro en Polea Alta',
  'Jalón en Pronación en Máquina',
  'Jalón en Pronación en Polea Alta',
  'Jalón en Supinación con Bandas',
  'Jalón en Supinación en Máquina',
  'Jalón en Supinación en Polea Alta',
  'Jalón Neutro con Bandas',
  'Jalón Trasero Abierto en Pronación en Polea Alta',
  'Janda Sit-up',
  'Jumping Jacks',
  'Krankcycle',
  'Máquina de Remo',
  'Máquina de Step',
  'Máquina Elíptica',
  'Máquina Escaladora',
  'Marcha Horizontal Aislada con pierna extendida',
  'Marcha Horizontal Alterna',
  'Marcha Horizontal Alterna con palmada',
  'Media Sentadilla con Barra',
  'Media Sentadilla con Mancuernas',
  'Mountain Climbers',
  'Pájaros Aislados con Mancuerna',
  'Pájaros Aislados en Polea',
  'Pájaros de pie con Bandas',
  'Pájaros de pie con Mancuernas',
  'Pájaros sentado con Mancuernas',
  'Paso lateral con Banda',
  'Patadas altas',
  'Patadas Traseras Alternas con Mancuernas',
  'Patadas Traseras con Mancuernas',
  'Patadas Traseras en Polea',
  'Peso Muerto a una pierna con Barra',
  'Peso Muerto a una pierna con Mancuernas',
  'Peso Muerto Abierto con Mancuerna',
  'Peso Muerto Asistido con Barra',
  'Peso Muerto con Banda',
  'Peso Muerto con Bandas',
  'Peso Muerto con Barra',
  'Peso Muerto con Mancuernas',
  'Peso Muerto en Polea',
  'Peso Muerto en Punta',
  'Peso Muerto Rígido con Mancuernas',
  'Peso Muerto Rumano con Barra',
  'Peso Muerto Rumano con Mancuernas',
  'Peso Muerto Sumo con Barra',
  'Pies rápidos agachado',
  'Pies rápidos de pie',
  'Plancha',
  'Plancha con rodillas',
  'Plancha Lateral',
  'Plancha Lateral Inclinada',
  'Pliegue completo con Bandas',
  'Pliegue completo entre Poleas',
  'Plyo Jacks',
  'Post-Workout',
  'Pre-Workout',
  'Prensa Inclinada',
  'Prensa Inclinada Cerrada',
  'Press a una mano con Barra',
  'Press Abierto Neutro con Mancuernas',
  'Press Aislado en Punta',
  'Press Aislado en Supinación con Mancuerna',
  'Press Arnold Abierto con Mancuernas',
  'Press Arnold con Mancuernas',
  'Press Banca Abierto con Barra',
  'Press Banca Abierto Inverso con Barra',
  'Press Banca Aislado con Polea',
  'Press Banca Alterno con Mancuernas',
  'Press Banca Cerrado con Barra',
  'Press Banca con Bandas',
  'Press Banca con Barra',
  'Press Banca con giro con Mancuernas',
  'Press Banca con Mancuernas',
  'Press Banca en Máquina',
  'Press Banca en Supinación Aislado con Mancuerna',
  'Press Banca Neutro con Mancuernas',
  'Press Cerrado con Barra',
  'Press Cerrado en Máquina Smith',
  'Press Cerrado en Supinación con Barra',
  'Press Cerrado Neutro con Mancuernas',
  'Press Cubano Circular con Mancuernas',
  'Press Cubano con Mancuernas',
  'Press Declinado Aislado con Mancuerna',
  'Press Declinado Aislado con Polea',
  'Press Declinado con Barra',
  'Press Declinado con Mancuernas',
  'Press Declinado Inverso con Barra',
  'Press Declinado Neutro con Mancuernas',
  'Press Francés con Bandas',
  'Press Francés con Barra',
  'Press Francés con Barra Z',
  'Press Francés con Mancuernas',
  'Press Francés con Polea',
  'Press Francés Declinado Abierto con Barra Z',
  'Press Francés Declinado Cerrado con Barra Z',
  'Press Francés Declinado con Barra',
  'Press Francés Inclinado Alterno con Mancuernas',
  'Press Francés Inclinado con Polea',
  'Press Francés Inverso con Barra',
  'Press Francés Neutro con Polea',
  'Press Francés tras nuca con Barra',
  'Press Frontal a una mano en Polea',
  'Press Frontal Cerrado con Poleas',
  'Press Frontal Cerrado en Máquina',
  'Press Frontal con Poleas',
  'Press Frontal en Máquina',
  'Press Frontal en Pronación con Bandas',
  'Press Frontal Inclinado con Bandas',
  'Press Frontal Inferior en Máquina',
  'Press Frontal Neutral con Banda',
  'Press Frontal Neutral con Polea',
  'Press Frontal Superior en Máquina',
  'Press Horizontal con Mancuernas',
  'Press Inclinado Aislado con Mancuerna',
  'Press Inclinado Aislado con Polea',
  'Press Inclinado Cerrado con Barra',
  'Press Inclinado Cerrado Neutro con Mancuerna',
  'Press Inclinado con Barra',
  'Press Inclinado en Máquina',
  'Press Inclinado en Supinación con Barra',
  'Press Inclinado en Supinación con giro con Mancuernas',
  'Press Inclinado en Supinación con Mancuernas',
  'Press Inclinado Inverso con Barra',
  'Press Militar Abierto con Barra',
  'Press Militar Aislado con Banda',
  'Press Militar Cerrado con Barra',
  'Press Militar Cerrado en Polea',
  'Press Militar con Bandas',
  'Press Militar con Barra',
  'Press Militar con giro con Mancuernas',
  'Press Militar Declinado en Pronación en Máquina',
  'Press Militar en Polea',
  'Press Militar en Pronación con Mancuernas',
  'Press Militar en Pronación en Máquina',
  'Press Militar en Supinación con Barra Z',
  'Press Militar en Supinación con Mancuernas',
  'Press Militar Inclinado en Pronación en Máquina',
  'Press Militar Inclinado Neutro en Máquina',
  'Press Militar Libre',
  'Press Militar Libre entre Bancos',
  'Press Militar Mixto con Barra',
  'Press Militar Neutro Alterno en Polea',
  'Press Militar Neutro con Mancuernas',
  'Press Militar Neutro en Máquina',
  'Press Militar Trasero con Bandas',
  'Press Militar Trasero con Barra',
  'Press Scott con Mancuernas',
  'Press Svend',
  'Puente Lateral',
  'Puente Lateral con Abducción de Cadera',
  'Puente Lateral con Mancuerna',
  'Puente Lateral Declinado',
  'Puente Lateral Declinado Aislada',
  'Pullover con Barra',
  'Pullover con Barra Z',
  'Pullover con cuerda en Polea',
  'Pullover con Mancuerna',
  'Pullover Declinado Cerrado con Barra',
  'Pullover Declinado con Barra',
  'Pullover Extenso con Mancuernas',
  'Pulse Up',
  'Remo Aislado con Barra',
  'Remo Aislado con Mancuerna',
  'Remo Aislado en Pronación en Máquina Smith',
  'Remo Aislado en Punta',
  'Remo Aislado Neutro en Máquina Smith',
  'Remo al mentón Cerrado con Barra Z',
  'Remo al mentón con Banda',
  'Remo al mentón con Barra',
  'Remo al mentón con Mancuernas',
  'Remo al mentón en Polea',
  'Remo al mentón Horizontal en Polea',
  'Remo Colgado en Pronación',
  'Remo Colgado en Supinación',
  'Remo con giro Aislado en Polea Baja',
  'Remo Cruzado en Polea Alta',
  'Remo Declinado Abierto en Pronación en Polea',
  'Remo Declinado Alterno con Bandas',
  'Remo Declinado en Pronación en Polea',
  'Remo Declinado Neutro en Pronación en Polea',
  'Remo en Barra T en Pronación',
  'Remo en Barra T en Supinación',
  'Remo en Pronación Abierto con Barra',
  'Remo en Pronación con Barra',
  'Remo en Pronación con Mancuernas',
  'Remo en Punta',
  'Remo en Supinación con Barra',
  'Remo en Supinación con Mancuernas',
  'Remo en Supinación en Máquina Smith',
  'Remo Horizontal Abierto en Pronación en Polea',
  'Remo Horizontal Aislado con Banda',
  'Remo Horizontal Aislado en Polea',
  'Remo Horizontal Cerrado en Pronación en Polea',
  'Remo Horizontal Cerrado Neutro Amplio en Polea',
  'Remo Horizontal Cerrado Neutro en Polea',
  'Remo Horizontal con Bandas',
  'Remo Horizontal en Pronación en Máquina',
  'Remo Horizontal en Pronación en Polea',
  'Remo Horizontal en Supinación en Máquina',
  'Remo Horizontal Neutro en Máquina',
  'Remo Horizontal Neutro en Polea',
  'Remo Horizontal Superior con Cuerda en Polea',
  'Remo Inclinado Alterno con Bandas',
  'Remo Inclinado en Pronación con Barra',
  'Remo Inclinado en Pronación con Mancuernas',
  'Remo Inclinado en Supinación con Barra',
  'Remo Inclinado en Supinación con Mancuernas',
  'Remo Inclinado Neutro con Mancuernas',
  'Remo Inferior Aislado con Banda',
  'Remo Inferior Aislado en Polea Baja',
  'Remo Inferior en Pronación en Polea Baja',
  'Remo Libre Declinado con Cuerdas',
  'Remo Libre Horizontal Abierto con Cuerdas',
  'Remo Libre Horizontal Cerrado con Cuerda',
  'Remo Libre Inclinado Abierto con Cuerda',
  'Remo Libre Inclinado Cerrado con Cuerda',
  'Remo Neutro con Mancuernas',
  'Remo Superior Aislado con Banda',
  'Remo Superior Aislado con Mancuerna',
  'Remo Superior Aislado en Polea',
  'Remo Superior con Bandas',
  'Remo Superior con Cuerda en Polea',
  'Remo Superior en Polea',
  'Remo Superior en Pronación en Polea',
  'Remo Superior Trasero con Mancuernas',
  'Retracción Escapular Colgado',
  'Retracción Escapular entre Bancos',
  'Rodilla al codo',
  'Rodilla al codo con giro',
  'Rodilla al codo con sentadilla',
  'Roll Reverse Crunch',
  'Rotación Concentrada con Mancuerna',
  'Rotación de Aductor Externa con Banda',
  'Rotación de Aductor Interna con Banda',
  'Rotación de Cadera Externa con Banda',
  'Rotación de Cadera Interna con Banda',
  'Rotación Externa Aislada con Mancuerna',
  'Rotación Externa Aislada en Polea',
  'Rotación Externa Concentrada con Mancuerna',
  'Rotación Interna Aislada en Polea',
  'Rotación Vertical Aislada con Mancuerna',
  'Rotación Vertical Aislada en Polea',
  'Russian Twist',
  'Russian Twist con Mancuerna',
  'Russian Twist en Fitball con Polea',
  'Salto alterno en el sitio',
  'Salto con Cuerda Alterno Alto',
  'Salto con Cuerda Alterno Normal',
  'Salto con Cuerda Alto',
  'Salto con Cuerda Lateral',
  'Salto con Cuerda Normal',
  'Salto con desplazamiento lateral',
  'Salto con desplazamiento lateral cruzado',
  'Salto de esquí',
  'Saltos rodillas en cuclillas con Barra',
  'Sentadilla a una pierna con Banda Debajo',
  'Sentadilla a una pierna con Banda Delante',
  'Sentadilla a una pierna con Barra',
  'Sentadilla a una pierna con Mancuerna',
  'Sentadilla Abierta con Mancuerna',
  'Sentadilla Aislada Asistida con Cuerda',
  'Sentadilla Asistida con Mancuerna',
  'Sentadilla Cerrada Inclinada en Máquina',
  'Sentadilla con Banda',
  'Sentadilla con Barra',
  'Sentadilla con Mancuernas',
  'Sentadilla con Poleas',
  'Sentadilla con salto con Barra',
  'Sentadilla con salto con Mancuernas',
  'Sentadilla en Máquina',
  'Sentadilla en Pared con Mancuernas',
  'Sentadilla en Punta',
  'Sentadilla en zancada con Barra',
  'Sentadilla en zancada inclinada con Barra',
  'Sentadilla en zancada inclinada con Mancuernas',
  'Sentadilla Profunda con Barra',
  'Sentadilla Sumo con Barra',
  'Sentadilla Sumo con Mancuerna',
  'Sentadilla Sumo Inclinada en Máquina',
  'Serratos Aislados en Polea',
  'Serratos con Cuerda en Polea',
  'Serratos con giro en Polea',
  'Serratos Inclinados Cerrados con Barra en Polea',
  'Serratos Inclinados con Barra en Polea',
  'Serratos Inferiores con Barra en Polea',
  'Sit Up con Bandas',
  'Sit Up en Fitball',
  'Sit Up en Máquina',
  'Skips',
  'Split Jacks',
  'Sprints con rodilla alta',
  'Squat Tuck Jumps',
  'Step Up',
  'Step Up con Banda',
  'Step Up con Barra',
  'Step Up con Mancuernas',
  'Step Up Lateral',
  'Tuck Jumps',
  'Wheel Rollout de pie',
  'Wheel Rollout de rodillas',
  'Wrist Roller',
  'Zancada con salto',
  'Zancada Delantera con Mancuernas',
  'Zancada Delantera en Polea',
  'Zancada Lateral con Barra',
  'Zancada Lateral con Mancuerna',
  'Zancada Lateral Cruzada con Barra',
  'Zancada Lateral Cruzada con Mancuerna',
  'Zancada Lateral en Polea',
  'Zancada Trasera con Barra',
  'Zancada Trasera con Mancuernas',
  'Zancada Trasera en Polea',
  'Zancada Trasera en Punta',
  'Zancadas con salto'
  );

-- 1) Previsualizar cuántos tipos se borrarán:
select count(*) as tipos_a_borrar from target_ids;

-- 2) Borrado real:
delete from public.serie
where ejercicio_id in (
  select e.id
  from public.ejercicio e
  where e.tipo_ejercicio_id in (select id from target_ids)
);

delete from public.ejercicio
where tipo_ejercicio_id in (select id from target_ids);

delete from public.rutina_ejercicio
where tipo_ejercicio_id in (select id from target_ids);

delete from public.tipo_ejercicio
where id in (select id from target_ids);

commit;
