INSERT INTO public.tipo_ejercicio (nombre, descripcion) VALUES

-- --- PECHO (CHEST) ---
('Press de Banca con Barra', 'Pecho - Fuerza básica. Compuesto.'),
('Press de Banca con Mancuernas', 'Pecho - Mayor rango de movimiento.'),
('Press Inclinado con Barra', 'Pecho Superior - Compuesto.'),
('Press Inclinado con Mancuernas', 'Pecho Superior - Aislamiento y control.'),
('Press Declinado', 'Pecho Inferior - Barra o Mancuernas.'),
('Aperturas con Mancuernas (Flyes)', 'Pecho - Estiramiento bajo carga.'),
('Cruce de Poleas (Alto a Bajo)', 'Pecho Inferior - Contracción constante.'),
('Cruce de Poleas (Bajo a Alto)', 'Pecho Superior - Contracción constante.'),
('Peck Deck (Mariposa)', 'Pecho - Aislamiento en máquina.'),
('Fondos en Paralelas (Dips)', 'Pecho/Tríceps - Calistenia lastrada.'),
('Flexiones (Push-ups)', 'Pecho/Core - Peso corporal.'),
('Flexiones Diamante', 'Pecho/Tríceps - Enfoque tríceps.'),
('Press de Banca en Multipower (Smith)', 'Pecho - Guiado y seguro.'),
('Pull-over con Mancuerna', 'Pecho/Serratos - Expansión caja torácica.'),

-- --- ESPALDA (BACK) ---
('Dominadas Pronas (Pull-ups)', 'Espalda (Dorsal) - Anchura.'),
('Dominadas Supinas (Chin-ups)', 'Espalda/Bíceps - Grosor y fuerza.'),
('Dominadas Neutras', 'Espalda - Enfoque braquial.'),
('Jalón al Pecho (Polea Alta)', 'Espalda - Alternativa a dominadas.'),
('Remo con Barra (Bent Over Row)', 'Espalda - Grosor y fuerza bruta.'),
('Remo con Mancuerna a una mano', 'Espalda - Unilateral, corrección asimetrías.'),
('Remo Gironda (Polea Baja)', 'Espalda - Control y contracción.'),
('Remo en Máquina T', 'Espalda - Carga pesada seguro.'),
('Remo Pendlay', 'Espalda - Potencia desde el suelo.'),
('Pull-over en Polea Alta', 'Espalda (Dorsal) - Aislamiento puro (Dorian Yates).'),
('Peso Muerto Convencional', 'Espalda Baja/Isquios - Fuerza total.'),
('Peso Muerto Sumo', 'Piernas/Cadera - Enfoque glúteo.'),
('Rack Pulls', 'Espalda - Parte final del peso muerto.'),
('Hiperextensiones (Lumbares)', 'Espalda Baja - Salud lumbar.'),
('Face Pull', 'Hombro Posterior/Trapecio - Salud postural.'),
('Encogimientos con Barra (Shrugs)', 'Trapecio - Parte superior.'),

-- --- PIERNAS (LEGS) ---
('Sentadilla Trasera (Back Squat)', 'Piernas - El rey de los ejercicios.'),
('Sentadilla Frontal', 'Cuádriceps - Mayor énfasis anterior.'),
('Sentadilla Goblet', 'Cuádriceps - Principiantes/Calentamiento.'),
('Prensa de Piernas 45º', 'Cuádriceps - Carga alta sin fatiga espalda.'),
('Prensa Hack', 'Cuádriceps - Aislamiento guiado.'),
('Zancadas (Lunges) con Mancuernas', 'Piernas - Unilateral dinámico.'),
('Sentadilla Búlgara', 'Piernas/Glúteo - El mejor unilateral.'),
('Extensión de Cuádriceps', 'Cuádriceps - Aislamiento final.'),
('Peso Muerto Rumano (RDL)', 'Isquios/Glúteo - Cadena posterior.'),
('Curl Femoral Tumbado', 'Isquios - Aislamiento.'),
('Curl Femoral Sentado', 'Isquios - Mayor estiramiento.'),
('Hip Thrust con Barra', 'Glúteo - Empuje de cadera pesado.'),
('Puente de Glúteo (Glute Bridge)', 'Glúteo - Peso corporal o mancuerna.'),
('Patada de Glúteo en Polea', 'Glúteo - Aislamiento.'),
('Elevación de Talones de Pie', 'Gemelo - Gastrocnemio.'),
('Elevación de Talones Sentado', 'Gemelo - Sóleo.'),
('Abductores en Máquina', 'Cadera/Glúteo Medio.'),
('Aductores en Máquina', 'Interior del muslo.'),

-- --- HOMBROS (SHOULDERS) ---
('Press Militar con Barra (Overhead)', 'Hombro - Fuerza vertical.'),
('Press Militar con Mancuernas', 'Hombro - Estabilidad.'),
('Press Arnold', 'Hombro - Recorrido completo.'),
('Elevaciones Laterales con Mancuernas', 'Hombro Lateral - Amplitud.'),
('Elevaciones Laterales en Polea', 'Hombro Lateral - Tensión constante.'),
('Pájaros con Mancuernas', 'Hombro Posterior.'),
('Elevaciones Frontales', 'Hombro Anterior.'),
('Remo al Mentón (Upright Row)', 'Hombro Lateral/Trapecio.'),

-- --- BRAZOS (ARMS) ---
('Curl de Bíceps con Barra (Z o Recta)', 'Bíceps - Constructor de masa.'),
('Curl con Mancuernas Alterno', 'Bíceps - Supinación.'),
('Curl Martillo', 'Bíceps/Braquial - Anchura del brazo.'),
('Curl Predicador (Banco Scott)', 'Bíceps - Aislamiento estricto.'),
('Curl Concentrado', 'Bíceps - Pico del bíceps.'),
('Curl en Polea Baja', 'Bíceps - Tensión continua.'),
('Press Francés con Barra Z', 'Tríceps - Cabeza larga.'),
('Rompecráneos (Skullcrushers)', 'Tríceps - Cabeza larga.'),
('Extensión de Tríceps en Polea Alta', 'Tríceps - Cabeza lateral.'),
('Extensión de Tríceps con Cuerda', 'Tríceps - Énfasis final.'),
('Fondos entre Bancos', 'Tríceps - Peso corporal.'),
('Patada de Tríceps', 'Tríceps - Contracción final.'),
('Press de Banca Agarre Cerrado', 'Tríceps - Compuesto pesado.'),

-- --- CORE / ABS ---
('Plancha Abdominal (Plank)', 'Core - Estabilidad isométrica.'),
('Plancha Lateral', 'Oblicuos.'),
('Crunch Abdominal', 'Recto abdominal.'),
('Elevación de Piernas Colgado', 'Abdominales Inferiores.'),
('Rueda Abdominal (Ab Wheel)', 'Core - Anti-extensión avanzada.'),
('Russian Twist', 'Oblicuos - Rotacional.'),
('Leñador en Polea (Woodchopper)', 'Oblicuos - Funcional.'),
('Vacuum Abdominal', 'Transverso - Cintura estrecha.'),

-- --- CARDIO / CROSSFIT / OLÍMPICOS ---
('Burpees', 'Full Body - Metabólico.'),
('Salto al Cajón (Box Jump)', 'Piernas - Potencia.'),
('Kettlebell Swing', 'Cadena Posterior - Potencia.'),
('Clean & Jerk (Dos Tiempos)', 'Olímpico - Potencia total.'),
('Snatch (Arrancada)', 'Olímpico - Técnica y potencia.'),
('Remo en Concept2', 'Cardio - Full Body.'),
('Air Bike (Assault Bike)', 'Cardio - Alta intensidad.'),
('Saltar a la Comba', 'Cardio - Coordinación.');

ON CONFLICT (nombre) DO NOTHING;